# Generated by Django 4.2.3 on 2023-07-17 23:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VSComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], size=None)),
                ('ignore_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], size=None)),
                ('subscribes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VSVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], size=None)),
                ('description', models.TextField(default='My new video')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_videoserviceapp.vsuser')),
                ('comments', models.ManyToManyField(through='svo_videoserviceapp.CommentVideo', to='svo_videoserviceapp.vscomment')),
            ],
        ),
        migrations.AddField(
            model_name='vscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_videoserviceapp.vsuser'),
        ),
        migrations.AddField(
            model_name='commentvideo',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_videoserviceapp.vscomment'),
        ),
        migrations.AddField(
            model_name='commentvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_videoserviceapp.vsvideo'),
        ),
    ]
