# Generated by Django 4.2.3 on 2023-07-19 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('svo_videoserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsvideo',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
