# Generated by Django 4.2.3 on 2023-07-19 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svo_videoserviceapp', '0002_vsvideo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vscomment',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vsuser',
            name='black_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vsuser',
            name='ignore_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vsuser',
            name='subscribes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vsvideo',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
    ]
